### ISSUE TITLE
improve performance

### ISSUE THREAD

**Issue by matt-long** [marbl-ecosys/feisty#21]
Possible low hanging fruit:
-  might be to refactor process.py (#3)
- enable `dask` in driver
- enable SciPy ODE solvers

**Comment by mnlevy1981** [comment]
Old update (mentioned in various meetings, but I don't see any comments on github about it):

Addressing #3 helped some, but it turned out the big performance hit came from I/O -- namely, creating a giant xarray Dataset to store all of the model output. Introducing a `time_levs_per_ds` parameter and then concatenating those smaller datasets at the end of the run got us in line with the matlab performance numbers.

****

**New update**

I'm currently looking at `dask.delayed` to parallelize the driver, and in my sandbox I can run

```py3
feisty_drivers = feisty_driver.split(9)
```

To create a list of 9 drivers that have divided the `X` coordinate of the original driver into 9 smaller chunks. In theory, it should take ~10 seconds per year to integrate each of these chunks, and if I could do that in parallel then we'd see a pretty good performance boost (even accounting for the need to stitch the 9 output datasets back together).

I'm running into trouble after the above call, though. The next step is

```py3
tmp_output = []
for small_driver in feisty_drivers:
    tmp_output.append(dask.delayed(small_driver.run)(nsteps))
```

To create a list of dask-delayed tasks. I'm not entirely clear on how to proceed from there, though; `dask.compute(*tmp_output)` results in a `CancelledError`. `dask.compute(tmp_output[0])` appears to compute a single element of the list, but it must have lost the connection with the original `feisty_drivers` list because `feisty_drivers[0]._ds` does not exist when the `dask.compute()` call is finished (and if I loop through `tmp_output` to run `dask.compute()` then I'm running the compute calls serially rather than in parallel). So there's still some work to do...
